{
 "title": "Projeto Korp - Monitoramento de Serviço",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_availability", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taxa de Requisições por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "Requisições em {{path}}" }
   ]
  },
  {
   "title": "Volume Total de Requisições Absolutas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "Total" }
   ]
  }
 ]
}