server {
    listen 80;
    server_name localhost;
    location / {
        # Utilizando o nome do serviço como dominio
        proxy_pass http://http-server-projeto-korp:8080;

        # Configurações de proxy para encaminhar os headers corretos
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}