---
- name: Provisionamento http-server-projeto-korp
  hosts: servers
  become: true

  vars:
    project_path: "{{ playbook_dir | dirname }}"

  tasks:
    - name: Baixando o script oficial de instalação universal da Docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
        
    - name: Executando o script de instalação do Docker
      ansible.builtin.command:
        cmd: /tmp/get-docker.sh
      register: docker_install_result
      changed_when: true

    - name: Verificando status do serviço Docker e configurando para inicialização automatica
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Iniciando infraestrutura de containers com Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --build
        chdir: "{{ project_path }}"
      register: compose_output
      changed_when: true

    - name: Validando resposta pelo proxy com retries
      ansible.builtin.uri:
        url: "http://localhost:80/projeto-korp"
        method: GET
        return_content: true
        status_code: 200
      register: http_response
      until: "http_response.status == 200"
      retries: 20
      delay: 3

    - name: Confirmando sucesso com exibição de resposta no console
      ansible.builtin.debug:
        msg: "NGINX respondeu: {{ http_response.content }}"