---
- name: Provisionamento http-server-projeto-korp
  hosts: servers
  become: true

  vars:
    project_path: "/home/mauricio/http-server-projeto-korp-challenge"

  tasks:
    - name: Instalando pre-requisitos do sistema
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Criando diretório de chaves isolado no ubuntu e definindo permissões
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Fazendo o download da chave GPG oficial do Docker e salvando no diretório de chaves
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Adicionando o repositório oficial do Docker para APT
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      # Utilizando '{{ ansible_distribution_release }}' para resolver dinamicamente a versão do docker (ex: noble, jammy).

    - name: Instalando o Docker Engine e o Docker Compose Plugin via APT
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Verificando status do serviço Docker e configurando para inicialização automatica
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Iniciando infraestrutura de containers com Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --build
        chdir: "{{ project_path }}"
      register: compose_output
      changed_when: true

    - name: Validando resposta pelo proxy com retries
      ansible.builtin.uri:
        url: "http://localhost:80/projeto-korp"
        method: GET
        return_content: true
        status_code: 200
      register: http_response
      until: "http_response.status == 200"
      retries: 20
      delay: 3

    - name: Confirmando sucesso com exibição de resposta no console
      ansible.builtin.debug:
        msg: "NGINX respondeu: {{ http_response.content }}"